/*
 * generated by Xtext
 */
package org.eclipse.xtext.services.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.services.ui.internal.ServicesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ServicesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ServicesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ServicesActivator.getInstance().getInjector(ServicesActivator.ORG_ECLIPSE_XTEXT_SERVICES_SERVICES);
	}
	
}
