/*
* generated by Xtext
*/
package org.eclipse.xtext.services.ui.contentassist;

import org.eclipse.xtext.services.ui.contentassist.AbstractServicesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ServicesProposalProvider extends AbstractServicesProposalProvider {

}
