/*
 * generated by Xtext
 */
package org.eclipse.xtext.services;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ServicesRuntimeModule extends org.eclipse.xtext.services.AbstractServicesRuntimeModule {

}
