/*
 * generated by Xtext
 */
package org.eclipse.xtext.services.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ServicesUiModule extends org.eclipse.xtext.services.ui.AbstractServicesUiModule {
	public ServicesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
