/*
* generated by Xtext
*/
package org.eclipse.xtext.services.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.services.services.ServicesGrammarAccess;

public class ServicesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ServicesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.services.parser.antlr.internal.InternalServicesParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.services.parser.antlr.internal.InternalServicesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Component";
	}
	
	public ServicesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ServicesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
